### ISSUE TITLE
Add a workflow for adding issues/PRs to projects

### ISSUE THREAD

**Issue by jcgruenhage** [famedly/github-workflows#1]
The action for this is https://github.com/actions/add-to-project, and we have a workflow for that in a few repositories, for example https://github.com/famedly/barad-dur/blob/main/.github/workflows/main.yml. This should be a properly parameterized workflow though, so that we have to only specify the project per repo, and not also the access token, what version of the action to use, etc.

**Comment by CherryKitten** [comment]
Merged into all of our repos!

**Comment by jcgruenhage** [comment]
Merged into all infra repos at least, but this should probably also be used by @famedly/product, so maybe @nikzen should take a look here too? Right now the product repos use the action directly instead of abstracting it away with a workflow.

**Comment by jcgruenhage** [comment]
Either way: Thanks for your work on this :)

**Comment by CherryKitten** [comment]
> Merged into all infra repos at least, but this should probably also be used by @famedly/product, so maybe @nikzen should take a look here too? Right now the product repos use the action directly instead of abstracting it away with a workflow.

Yeah, I'd personally consider this done with the workflow being created and tested in the infra repos, and now the other teams should import this into their own repos if they need it
